# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.6", "5.4.2", "luajit-2.1.0-beta3"]

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - uses: leafo/gh-actions-luarocks@v4.0.0
    - name: prepare
      run: |
        sudo apt-get -y install libev-dev
        luarocks install lua_cliargs 2.0-1
        luarocks install luacov
        luarocks install busted 1.11.1-2
        luarocks install lua-ev
    # fix issue of busted 1.11.1-2, see https://github.com/Olivine-Labs/busted/issues/290
    - name: fix busted
      run: cp $(which busted_bootstrap) $(which busted)
    - name: test
      run: |
        busted
